### ISSUE TITLE
Cannot run dev in Linux

### ISSUE THREAD

**Issue by pnhuyduy** [yingpengsha/electron-vite-quick-start#8]
OS: Linux Mint 20.3
I install the template then run `yarn start` but nothing happen.
![image](https://user-images.githubusercontent.com/46210597/166611456-93b9fb60-3790-4a76-8f57-5c649e4337a2.png)

**Comment by yingpengsha** [comment]
Copy that,  I‘m installing the VIRTUAL machine.

![image](https://user-images.githubusercontent.com/37143265/166855287-ca90fc35-2d24-4587-9926-97617dfa386a.png)

**Comment by pnhuyduy** [comment]
I found where the problem causes:
`scripts/dev-runner.js`
```javascript
electronProcess = spawn(electron, args, {env: {
    RENDERER_URL
  }})

// remove third param
electronProcess = spawn(electron, args)
```

**Comment by yingpengsha** [comment]
I found a solution:

```diff
electronProcess = spawn(electron, args, {env: {
+ ...process.env,
  RENDERER_URL
}})
```

It's useful in my experiment. You can try it out, and if it work, it will be merged into the main code branch after I've done a thorough test.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/37143265/166875298-1a5c2ff3-af32-412b-82cb-5937c688bc47.png">

**Comment by pnhuyduy** [comment]
Thanks a lot. It works now.
